import { createClient } from 'npm:@supabase/supabase-js@2'
const corsHeaders={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'}
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...corsHeaders,'Content-Type':'application/json; charset=utf-8'}})
const digits=(v:unknown)=>String(v||'').replace(/\D/g,'')
function cpfValido(v:unknown){const c=digits(v);if(c.length!==11||/^(\d)\1{10}$/.test(c))return false;const calc=(base:string,p:number)=>{let s=0;for(let i=0;i<base.length;i++)s+=Number(base[i])*(p-i);const r=(s*10)%11;return r===10?0:r};return calc(c.slice(0,9),10)===Number(c[9])&&calc(c.slice(0,10),11)===Number(c[10])}
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:corsHeaders});if(req.method!=='POST')return json({error:'Método não permitido.'},405)
try{const url=Deno.env.get('SUPABASE_URL');const key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!url||!key)throw new Error('Configuração do Supabase indisponível.');const admin=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}})
const token=(req.headers.get('Authorization')||'').replace(/^Bearer\s+/i,'');if(!token)return json({error:'Sessão não encontrada.'},401);const{data:userData,error:userError}=await admin.auth.getUser(token);if(userError||!userData.user)return json({error:'Sessão inválida.'},401)
const{data:caller,error:callerError}=await admin.from('usuarios_perfis').select('perfil, ativo').eq('user_id',userData.user.id).single();if(callerError||!caller?.ativo||caller.perfil!=='admin')return json({error:'Apenas administradores podem gerenciar acessos.'},403)
const payload=await req.json();const action=String(payload.action||'create')
if(action==='list-pre-cadastros'){const{data,error}=await admin.from('pre_cadastro_profissionais').select('*').order('created_at',{ascending:false});if(error)throw error;return json({pre_cadastros:data||[]})}
if(action==='set-pre-cadastro-status'||action==='reject-pre-cadastro'){const id=String(payload.pre_cadastro_id||'');const status=action==='reject-pre-cadastro'?'recusado':(payload.status==='em_analise'?'em_analise':'pendente');const{error}=await admin.from('pre_cadastro_profissionais').update({status,observacoes_admin:String(payload.observacoes_admin||'').trim()||null,analisado_por:userData.user.id,analisado_em:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',id);if(error)throw error;return json({ok:true})}
if(action==='approve-pre-cadastro'){const id=String(payload.pre_cadastro_id||'');const password=String(payload.password||'');const status=payload.status==='inativo'?'inativo':'ativo';if(password.length<8)return json({error:'A senha deve ter pelo menos 8 caracteres.'},400)
const{data:pre,error:preError}=await admin.from('pre_cadastro_profissionais').select('*').eq('id',id).single();if(preError||!pre)return json({error:'Pré-cadastro não encontrado.'},404);if(pre.status==='aprovado')return json({error:'Este pré-cadastro já foi aprovado.'},400);if(!cpfValido(pre.cpf))return json({error:'O CPF do pré-cadastro é inválido.'},400)
const{data:cpfDup}=await admin.from('profissionais').select('id').eq('cpf',digits(pre.cpf)).maybeSingle();if(cpfDup)return json({error:'Já existe um profissional com este CPF.'},400);const{data:mailDup}=await admin.from('profissionais').select('id').ilike('email',pre.email).maybeSingle();if(mailDup)return json({error:'Já existe um profissional com este e-mail.'},400)
const{data:created,error:createError}=await admin.auth.admin.createUser({email:pre.email,password,email_confirm:true,user_metadata:{name:pre.nome}});if(createError)return json({error:createError.message},400);const authId=created.user.id
const{data:professional,error:pError}=await admin.from('profissionais').insert({auth_user_id:authId,nome:pre.nome,email:pre.email,telefone:pre.celular,especialidade:pre.especialidade,cpf:digits(pre.cpf),status,updated_at:new Date().toISOString()}).select('*').single();if(pError){await admin.auth.admin.deleteUser(authId);return json({error:pError.message},400)}
const{error:profileError}=await admin.from('usuarios_perfis').insert({user_id:authId,profissional_id:professional.id,nome:pre.nome,email:pre.email,perfil:'profissional',ativo:status==='ativo',updated_at:new Date().toISOString()});if(profileError){await admin.from('profissionais').delete().eq('id',professional.id);await admin.auth.admin.deleteUser(authId);return json({error:profileError.message},400)}
const{error:updateError}=await admin.from('pre_cadastro_profissionais').update({status:'aprovado',observacoes_admin:String(payload.observacoes_admin||'').trim()||null,analisado_por:userData.user.id,analisado_em:new Date().toISOString(),profissional_id:professional.id,updated_at:new Date().toISOString()}).eq('id',id);if(updateError)throw updateError;return json({ok:true,profissional:professional})}
// Mantém compatibilidade com as ações já existentes da função.
if(action==='list'){const[{data:profissionais,error:pError},{data:perfis,error:aError}]=await Promise.all([admin.from('profissionais').select('id, auth_user_id, nome, email, telefone, especialidade, status, created_at').order('nome',{ascending:true}),admin.from('usuarios_perfis').select('profissional_id, perfil, ativo')]);if(pError)throw pError;if(aError)throw aError;const by=new Map((perfis||[]).map((x:any)=>[x.profissional_id,x]));return json({profissionais:(profissionais||[]).map((p:any)=>({...p,perfil:by.get(p.id)?.perfil||'profissional',acesso_ativo:by.get(p.id)?.ativo??(p.status==='ativo')}))})}
if(action==='create'){const nome=String(payload.nome||'').trim(),email=String(payload.email||'').trim().toLowerCase(),password=String(payload.password||''),perfil=payload.perfil==='admin'?'admin':'profissional',telefone=String(payload.telefone||'').trim()||null,especialidade=String(payload.especialidade||'').trim()||null,status=payload.status==='inativo'?'inativo':'ativo';if(!nome||!email)return json({error:'Nome e e-mail são obrigatórios.'},400);if(password.length<8)return json({error:'A senha deve ter pelo menos 8 caracteres.'},400);const{data:created,error:createError}=await admin.auth.admin.createUser({email,password,email_confirm:true,user_metadata:{name:nome}});if(createError)return json({error:createError.message},400);const authId=created.user.id;const{data:professional,error:pError}=await admin.from('profissionais').insert({auth_user_id:authId,nome,email,telefone,especialidade,status,updated_at:new Date().toISOString()}).select('*').single();if(pError){await admin.auth.admin.deleteUser(authId);return json({error:pError.message},400)}const{error:profileError}=await admin.from('usuarios_perfis').insert({user_id:authId,profissional_id:professional.id,nome,email,perfil,ativo:status==='ativo',updated_at:new Date().toISOString()});if(profileError){await admin.from('profissionais').delete().eq('id',professional.id);await admin.auth.admin.deleteUser(authId);return json({error:profileError.message},400)}return json({profissional:professional,perfil})}
if(action==='set-profile'){const id=String(payload.profissional_id||''),perfil=payload.perfil==='admin'?'admin':'profissional',ativo=payload.ativo!==false;const{data:p,error:e}=await admin.from('profissionais').select('id, auth_user_id, nome, email').eq('id',id).single();if(e||!p?.auth_user_id)return json({error:'Profissional sem usuário de acesso vinculado.'},400);const{error}=await admin.from('usuarios_perfis').upsert({user_id:p.auth_user_id,profissional_id:p.id,nome:p.nome||'Profissional',email:p.email||'sem-email@protege.local',perfil,ativo,updated_at:new Date().toISOString()},{onConflict:'user_id'});if(error)throw error;return json({ok:true})}
if(action==='reset-password'){const id=String(payload.profissional_id||''),password=String(payload.password||'');if(password.length<8)return json({error:'A senha deve ter pelo menos 8 caracteres.'},400);const{data:p,error:e}=await admin.from('profissionais').select('auth_user_id').eq('id',id).single();if(e||!p?.auth_user_id)return json({error:'Profissional sem usuário de acesso vinculado.'},400);const{error}=await admin.auth.admin.updateUserById(p.auth_user_id,{password});if(error)throw error;return json({ok:true})}
return json({error:'Ação inválida.'},400)}catch(error){console.error(error);return json({error:error instanceof Error?error.message:'Erro inesperado.'},500)}})
